# Custom Layers
## Simple Dense Layer

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [2]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import Layer
from keras.models import Sequential
import numpy as np

# Set up gpu
physical_devices = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

In [3]:
class SimpleDense(Layer):
    def __init__(self, units=32):
        super(SimpleDense, self).__init__()
        self.units = units

    def build(self, input_shape):
        w_init = tf.random_normal_initializer()
        b_init = tf.zeros_initializer()

        self.w = tf.Variable(name='kernel', initial_value=w_init(shape=[input_shape[-1], self.units],
                                                                dtype='float32'),
                            trainable=True)
        self.b = tf.Variable(name='bias', initial_value=b_init(shape=[self.units], dtype='float32'),
                            trainable=True)

    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b

In [4]:
X = np.arange(1, 10).reshape(-1, 1)
X = X.astype('float32')
Y = 2 * X - 1
Y = Y.astype('float32')

In [5]:
simple_dense = SimpleDense(units=1)
print('initial predicted values are', simple_dense(X))
print('\n'.join([f'{var}' for var in simple_dense.trainable_variables]))

initial predicted values are tf.Tensor(
[[0.03857117]
 [0.07714234]
 [0.11571351]
 [0.15428467]
 [0.19285583]
 [0.23142701]
 [0.26999816]
 [0.30856934]
 [0.34714052]], shape=(9, 1), dtype=float32)
<tf.Variable 'simple_dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.03857117]], dtype=float32)>
<tf.Variable 'simple_dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>


In [6]:
model = Sequential([simple_dense])
model.compile(loss='mean_squared_error', optimizer=tf.optimizers.SGD())
model.fit(X, Y, epochs=5000, verbose=0);

In [7]:
print('initial values are', simple_dense(X))
print('\n'.join([f'{var}' for var in simple_dense.trainable_variables]))
print('Ground Truth is\n', Y)

initial values are tf.Tensor(
[[ 1.0000075]
 [ 3.000006 ]
 [ 5.0000043]
 [ 7.000003 ]
 [ 9.000002 ]
 [11.       ]
 [12.999998 ]
 [14.999996 ]
 [16.999996 ]], shape=(9, 1), dtype=float32)
<tf.Variable 'simple_dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.9999985]], dtype=float32)>
<tf.Variable 'simple_dense/bias:0' shape=(1,) dtype=float32, numpy=array([-0.99999094], dtype=float32)>
Ground Truth is
 [[ 1.]
 [ 3.]
 [ 5.]
 [ 7.]
 [ 9.]
 [11.]
 [13.]
 [15.]
 [17.]]
